### ISSUE TITLE
[Feature Request] Generate map images from the command-line

### ISSUE THREAD

**Issue by mid-kid** [Rangi42/polished-map#10]
Maybe it's just me. If it's just me I'll just hack this program to do this, but I think it'd be useful to provide the user a minimal command-line interface to export a map as an image. This would help for example with automatically updating a public gallery of map images on a wiki or the like.

The interface could work as follows:
```
polishedmap [options] <map>

Operation:
-i|--info                 Give autodetected information on the map [Default]
-o|--output <file.png>    Output a png image.

Options:
-p|--project <directory>  Set the project directory. [Default: Auto]
-w|--width <size>         Set the width of the map. [Default: Auto]
-h|--height <size>        Set the height of the map. [Default: Auto]
-t|--tileset <tileset>    Set the tileset of the map. [Default: Auto]
-l|--lighting <timeofday> Set the map's lighting. [Default: Day]
-m|--monochrome           Use monochrome colors.
-e|--extended             Allow 255-tile tileset.
```

**Comment by Rangi42** [comment]
Not a bad idea. I've already been using Python scripts for that, but it makes sense as an option for Polished Map.

**Comment by Rangi42** [comment]
Recorded in TODO.md.
