### ISSUE TITLE
[Feature Request] Quick Access tab

### ISSUE THREAD

**Issue by Mr-Gela** [Rangi42/polished-map#11]
Something such as, "after you open a blk from a folder, open the quick access tab, allowing you to travel through the files quickly". Additionally an "open->recent->(list)" tab at the top would be great too. Helps when you're working on a map several times, but would rather not have to browse the folder themselves.

![image](https://user-images.githubusercontent.com/42318572/44055777-b153b8ae-9f46-11e8-8c80-e0642494395f.png)

**Comment by Rangi42** [comment]
Recorded in TODO.md.
