### ISSUE TITLE
[Feature request] Support relative paths

### ISSUE THREAD

**Issue by mid-kid** [Rangi42/polished-map#17]
Right now, when opened through a terminal, `polishedmap maps/NewBarkTown.blk` won't work. I'd have to explicitly run `polishedmap "$PWD"/maps/NewBarkTown.blk`. While this isn't the biggest issue ever, it's definitely annoying.

**Comment by Rangi42** [comment]
Added to TODO.md. (I'm surprised this didn't work already.)
