### ISSUE TITLE
[Feature Request] Shift+scroll scrolls horizontally

### ISSUE THREAD

**Issue by mid-kid** [Rangi42/polished-map#21]
I know middle-click works, but a lot of programs let you scroll both vertically and with shift for horizontal scrolling, and that's a bit more natural to me.
If this is more of a toolkit issue, I'll report it there.

**Comment by Rangi42** [comment]
I don't have a scrollwheel mouse to test that with. Arrow keys and a trackpoint both work for horizontal or vertical scrolling.

If you hold down Shift and use a sideways-scrolling mouse wheel, what's supposed to happen? Does it get swapped to vertical?

**Comment by Rangi42** [comment]
So, I think this could be achieved by making the `FL_MOUSEWHEEL` case of `Fl_Scrollbar::handle(int event)` check for whether Shift is being held, but doing so in Polished Map would mean (a) extending `Fl_Scrollbar` and (b) reimplementing `Fl_Scroll` to use the new custom `Fl_Scrollbar` class. It would be better off as a built-in FLTK feature.

**Comment by mid-kid** [comment]
Alright. Thanks for figuring this out.
