### ISSUE TITLE
PM doesn't append .blk to file name after saving if .blk is removed

### ISSUE THREAD

**Issue by i0brendan0** [Rangi42/polished-map#22]
I'm making new maps and I found that if I edit the name of the file and end up removing ".blk" from the generated file name, it won't add ".blk" after the file name. Polished Map will show "Saved <File Name>" without ".blk" after saving for the first time and the file will be "<File Name>" without ".blk". If saved after the fact, saving (not save as) will continue to use the ".blk"-less file name. I'm on windows 7 if that matters.

**Comment by Rangi42** [comment]
That's the intended behavior; if you explicitly give your file a different extension, or none at all, Polished Map won't stop you.

**Comment by i0brendan0** [comment]
I have never seen a program do this. Not even for programs that save as multiple types of files like an image editor. If someone wants to change the file extension they should do so after its saved or select "all files" in the save window.
