### ISSUE TITLE
Battle Tower Outside should not load battle_tower.pal

### ISSUE THREAD

**Issue by i0brendan0** [Rangi42/polished-map#26]
That specific pal file is only loaded inside the battle tower (when battle_tower tileset is loaded). The outside uses a different tileset called battle_tower_outside which does not load that palette in game.

**Comment by Rangi42** [comment]
Its landmark is `BATTLE_TOWER`, so it looks for `battle_tower.pal` and finds it. Uncheck "Options → Auto-Load Special Lighting".

**Comment by i0brendan0** [comment]
Um, that's not at all how the game loads that palette. 
```asm
LoadSpecialMapPalette:
	ld a, [wMapTileset]
	cp TILESET_POKECOM_CENTER
	jr z, .pokecom_2f
	cp TILESET_BATTLE_TOWER
	jr z, .battle_tower
	cp TILESET_ICE_PATH
	jr z, .ice_path
	cp TILESET_HOUSE
	jr z, .house
	cp TILESET_RADIO_TOWER
	jr z, .radio_tower
	cp TILESET_MANSION
	jr z, .mansion_mobile
	jr .do_nothing
```

**Comment by Rangi42** [comment]
Polished Map supports special palettes for landmarks because Polished Crystal needs them. It's not reading the `LoadSpecialMapPalette` routine directly.

**Comment by i0brendan0** [comment]
Yes obviously it doesn't, but that shouldn't mean that it should have a palette when Crystal doesn't use the landmark for the palette. You didn't do that for any place that uses the ice_path tileset. That loads the special palette correctly.

**Comment by i0brendan0** [comment]
In fact, the battle_tower palette loads the correct lighting even without being associated with the BattleTower name. All the other special palette tilesets load the lighting correctly except for the mansion tileset.

**Comment by Rangi42** [comment]
There is no bug here. pal files are being loaded as described in the Help file.

**Comment by i0brendan0** [comment]
So just because it's a thing with Polished Crystal and not regular Crystal, you're forcing it to happen? And no, turning the option off isn't a solution. Then other maps won't have special lighting loaded even if the lighting would be correct. That's a great way to be.

**Comment by Rangi42** [comment]
Then you turn the option back on. Or rename the interior tileset+pal to `battle_tower_inside`. Or the landmark to `BATTLE_TOWER_IN_AND_OUT`. Lots of solutions.

Landmark-based palettes are useful; the problem isn't them, it's the name collision between pokecrystal's battle_tower tileset and landmark.
