### ISSUE TITLE
Persisting "0xc000007b" error

### ISSUE THREAD

**Issue by ApolloMaster** [Rangi42/polished-map#27]
I've been trying to get polishedmap running for a while now, but no matter how much i troubleshoot it, whether by reinstalling NET Framework, Visual C++, or PolishedMap itself, trying to install PolishedMap++, doing a disk check, the program always gives me this error.
![image](https://user-images.githubusercontent.com/40720415/63642874-567cf500-c694-11e9-94a3-047ed09d0099.png)

I've tried basically everything i can and i'm not sure what would be causing this, and my hack can't really go anywhere without it. Any help is appreciated, thanks.

**Comment by Rangi42** [comment]
No idea why that's happening. :/ 0xc000007b is a pretty generic error. If everything on your system is updated—.NET framework, video drivers, Windows updates, etc—and it's still happening, then you could follow the instructions to build your own copy.

**Comment by aaaaaa123456789** [comment]
0xC000007B (`STATUS_INVALID_IMAGE_FORMAT`) actually indicates a problem with one of the binaries. Whatever the problem is, rebuilding the binaries should help.

**Comment by Rangi42** [comment]
Maybe your polishedmap.exe download was corrupt? Try downloading the 4.4.0 release. Or if that still doesn't work, you can follow the instructions to build your own copy with Visual Studio.
