### ISSUE TITLE
linux mint install;  issue

### ISSUE THREAD

**Issue by blessedoise** [Rangi42/polished-map#28]
Linux Mint 18.1

this may be a 'linux newbie' error, so forgive me if I'm missing something obvious.

I'm following the install.md instructions step-by-step, pasting them into terminal to make sure everything is accurate. 

At the final `make` and `make install` steps, I receive the following error: 

`make: fltk-config: Command not found
g++ -c -std=c++11 -Isrc -Ires  -DNDEBUG -O3 -flto -march=native -o tmp/colors.o src/colors.cpp
src/colors.cpp:7:19: fatal error: FL/Fl.H: No such file or directory
 #include <FL/Fl.H>
                   ^
compilation terminated.
Makefile:55: recipe for target 'tmp/colors.o' failed
make: *** [tmp/colors.o] Error 1
`

FLTK _seems_ to be installing and configuring correctly, and I've verified that `/home/username/polished-map/lib/bin:` is in my $PATH, and that `fltk-config` is indeed inside this directory.  Yet, `make` and `make install` don't seem to be able to access it.  

I've tried cleaning and reinstalling FLTK, but otherwise I can't really find any information on how to proceed.   

Any insight would be greatly appreciated, as I'm quite new to all this.

**Comment by FredrIQ** [comment]
Can you issue fltk-config directly? If so, try to export PATH. As in, "export PATH=$PATH".

**Comment by blessedoise** [comment]
> Can you issue fltk-config directly? If so, try to export PATH. As in, "export PATH=$PATH".

I'm not sure I understand.  
I'm not familiar with what it means to "issue" a file directly.  When I ran `info issue` it described it as "a text file which contains a message or system identification
       to be printed before the login prompt".  Otherwise, as far as I can tell, `export PATH=$PATH` seems to just make the $PATH equal to itself. 

Searching for either of these things doesn't really help, as "issue" seems to return only information on issues people are having, or occasionally the issue file, and `export PATH=$PATH` is always followed by a : and the directory to be added to $PATH.

If you mean to somehow provide fltk-config to the install make process, the only solutions for that I can find involve changing the $PATH once again, which already points to the directory that fltk-config is in.

Sorry if I'm not understanding, but this is like day 3 on linux for me, I decided to try this after the nightmare that is cygwin.

**Comment by Rangi42** [comment]
Did you run `export PATH="$PWD/lib/bin:$PATH"` before `make`?

**Comment by Rangi42** [comment]
"issue fltk-config" as in "if you type `fltk-config` and press Enter, what happens".

**Comment by blessedoise** [comment]
> Did you run `export PATH="$PWD/lib/bin:$PATH"` before `make`?

I did, I followed every instruction exactly in order up until the final `make` and `sudo make install` instructions.  Here is my $PATH:  
`/home/[username]/polished-map/lib/bin:/home/[username]/polished-map/lib/fltk-1.3.5-mod:/home/[username]/polished-map/lib/bin:/home/[username]/bin:/home/[username]/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
`
I added `/home/[username]/polished-map/lib/fltk-1.3.5-mod` just in case, didn't help.

>"issue fltk-config" as in "if you type fltk-config and press Enter, what happens".

When I do that, I get:
`Usage: fltk-config [OPTIONS]`  followed by 4 option categories (which makes me think it is installed).  I can also `info fltk-config` and get the info file.

**Comment by FredrIQ** [comment]
So it is clearly in your path. Did you perform the export command I told, just in case and try again? Because your problem sounds like if you configured PATH correctly, but never exported it.

**Comment by blessedoise** [comment]
> So it is clearly in your path. Did you perform the export command I told, just in case and try again? Because your problem sounds like if you configured PATH correctly, but never exported it.

Yes, I did.  Doing it again, right now - entering `export PATH=$PATH` in the polished-map directory and then entering `make` returns the same make error as before:  
`
g++ -c -std=c++11 -Isrc -Ires -I/home/[username]/polished-map/lib/fltk-1.3.5-mod/../include -I/home/vo/romhacks/polished-map/lib/fltk-1.3.5-mod/../include/FL/images -I/usr/include/freetype2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -DNDEBUG -O3 -flto -march=native -o tmp/colors.o src/colors.cpp
Assembler messages:
Fatal error: can't create tmp/colors.o: Permission denied
Makefile:55: recipe for target 'tmp/colors.o' failed
make: *** [tmp/colors.o] Error 1
`

What exactly is `export PATH=$PATH` supposed to do?  I tried googling it the first time it didn't work, and it doesn't seem to be a command on its own, it's only ever part of the command for adding directories to $PATH.

**Comment by Rangi42** [comment]
Try `sudo make`?

**Comment by blessedoise** [comment]
already had
`sudo make` returns the same error as `sudo make install`: 
`make: fltk-config: Command not found
g++ -c -std=c++11 -Isrc -Ires  -DNDEBUG -O3 -flto -march=native -o tmp/colors.o src/colors.cpp
src/colors.cpp:7:19: fatal error: FL/Fl.H: No such file or directory
 #include <FL/Fl.H>`  
`                  ^  `  
`compilation terminated.
Makefile:55: recipe for target 'tmp/colors.o' failed
make: *** [tmp/colors.o] Error 1`

**Comment by blessedoise** [comment]
I'm so confused.  `fltk-config` can clearly be found, since I can enter it into terminal and see its options, but when make tries to point to it, it can't find it?  I tried looking inside Makefile with gedit, but it looks like it's just entering `fltk-config` with the `--use-images --cxxflags` options, if I understand it correctly, both of which match options in the list I get entering `fltk-config`.

**Comment by coltongit** [comment]
Maybe install g++ and see if the issue goes away then, @blessedoise.

**Comment by Rangi42** [comment]
@blessedoise
