### ISSUE TITLE
Pasting Ctrl+P Ctrl+C screenshots into Discord doesn't work on Linux

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polished-map#39]
According to Chaos_lord2 (@chaos-lord).

**Comment by aaaaaa123456789** [comment]
Confirmed on Linux Mint 20.1.

**Comment by Rangi42** [comment]
There might be some commit in <https://github.com/fltk/fltk/tree/branch-1.3> that fixes this already.

**Comment by Rangi42** [comment]
This is still an issue with FLTK 1.3.6. It's also apparent when you try to paste into Imgur.

**Comment by Rangi42** [comment]
I've had this issue in Xubuntu with multiple other applications; e.g. Firefox can't right-click and Copy an image to paste it into Discord, I have to copy+paste the URL and rely on Discord to auto-embed it.

**Comment by Rangi42** [comment]
Closing since it's not specific to Polished Map or FLTK.
