### ISSUE TITLE
Bitdefender flagged install.bat and polished map exe as dangerous files

### ISSUE THREAD

**Issue by 25thbamofthetower** [Rangi42/polished-map#49]
Title

**Comment by Rangi42** [comment]
It's a false positive. They do this with a lot of small unfamiliar applications. There's a pinned message in [#tilemap-studio](https://discord.gg/QeufV6Hdcj) about this. You can help by reporting the false positive to [BitDefender](https://www.bitdefender.com/submit) and [Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission).
