### ISSUE TITLE
Does not run on arch linux

### ISSUE THREAD

**Issue by NeoUmbreon** [Rangi42/polished-map#58]
(I hope this is the right place for this)
Followed INSTALL.md, and polished map does not start with a seg fault. It worked fine for someone else despite arch not being explicitly supported, so clearly I must be missing something..
I know it's not affiliated, but the version of polished map on the aur has the same behavior.
Following tilemap studio's INSTALL.md works totally fine, though. Is there a difference between the two in terms of some dependency even though they seem super similar?
![Screenshot_2021-12-08_12-32-39](https://user-images.githubusercontent.com/46412722/145334018-20a65f25-f460-46af-86c3-88f1c16a2eb1.png)

**Comment by mid-kid** [comment]
I cannot reproduce this on Gentoo. It might be helpful to mention your GCC version (`gcc --version`), and possibly run the following to get a backtrace:
```
$ gdb bin/polishedmap
(gdb) r
# ... program will crash? ...
(gdb) bt
```
Also try `make debug` and see if the resulting `bin/polishedmapd` crashes. If it does, running the above with `gdb bin/polishedmapd` instead will give us more info to work with.

**Comment by NeoUmbreon** [comment]
![Screenshot_2021-12-09_13-15-44](https://user-images.githubusercontent.com/46412722/145454254-d7bd6e85-078f-4140-a4ff-e623fdcf8ba9.png)
![Screenshot_2021-12-09_13-24-04](https://user-images.githubusercontent.com/46412722/145454261-2743e2e1-512b-4871-883d-6086b9ecccb6.png)

**Comment by mid-kid** [comment]
![imatge](https://user-images.githubusercontent.com/1339276/145712362-05c1b3ae-2fd4-46bf-bab4-bda6378d0de0.png)
Can you make sure you have either the ubuntu, noto, droid or dejavu fonts installed?

**Comment by NeoUmbreon** [comment]
All I did was install noto-fonts-main from the aur and it launched. Thank you so much!!

**Comment by mid-kid** [comment]
Both noto-fonts, ttf-dejavu, and the other fonts mentioned are available in the main arch repositories. I recommend avoiding the aur if there's a solution in the main arch repository.

**Comment by NeoUmbreon** [comment]
I'm a fool, didn't notice that. Thanks
