### ISSUE TITLE
File->New fails if used before File->Open

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polished-map#60]
This might be because the pokecrystal project is on a mapped network drive, `\\wsl$\Ubuntu\home\<user>\pokecrystal`.

**Comment by EzioisAwesome56** [comment]
Encountering this same bug on the windows version, with the project NOT on a network share. (trying to point it at my project, H:\pret\pokecrystal claims invalid project dir, yet as you say, opening an existing map gets around the issue entirely)

![image](https://user-images.githubusercontent.com/21185626/153992472-5d7618a6-a773-42e6-8fe4-5456c092393b.png)
![image](https://user-images.githubusercontent.com/21185626/153992483-395e08aa-7586-40cf-9236-88b8a579cc8a.png)
