### ISSUE TITLE
[Feature Request] Block fill

### ISSUE THREAD

**Issue by mid-kid** [Rangi42/polished-map#7]
![](https://cdn.discordapp.com/attachments/317818988090621963/437355750935756800/trees2.gif)

This was requested by someone on the /rheg/ Discord.
It's a feature present in RPG Maker XP, that allows you dragging your mouse over an area to fill the entire area with a certain tile. Makes filling an entire map (especially the trees) from scratch much easier.

**Comment by mid-kid** [comment]
Drawing a good rectangle using the mouse is rather unintuitive and can easily go wrong -- try it. Not to mention that CTRL+Z has you redrawing the entire thing if you did it in one go.
I honestly believe such a feature would be rather beneficial and not too hard to implement, but feel free to reject this if you disagree (or take your time, I'm in no rush).

**Comment by Rangi42** [comment]
Doing this feature right would mean being able to temporarily show the edit, i.e. you click, drag and see a rectangle, and you can drag to a different spot and see the rectangle change before releasing the click to apply the edit. That's not easily adaptable to the current way of editing blocks.
