### ISSUE TITLE
Adapt to Mac Os

### ISSUE THREAD

**Issue by Lenmaz** [Rangi42/polished-map#8]
First of all, I have to say you have done an awesome work with polished-map.  You deserve big kudos for creating it.

Do you think it would possible to adapt the code so it could also work with Mac?

**Comment by Rangi42** [comment]
It's certainly possible. FLTK supports OS X. It would need customizations for the Mac menu bar, the UI theme, and a new build script that creates an app bundle.

**Comment by Rangi42** [comment]
Recorded in TODO.md.
