### ISSUE TITLE
Readme: Explain the overlay letters on some tiles.

### ISSUE THREAD

**Issue by mk-pmb** [Rangi42/polished-map#86]
In the screenshot, some tiles have overlay letters like B, C, O, or W. Would be nice if you could explain them below the screenshot.

**Comment by FrenchOrange** [comment]
B - Background Event (Sign or Hidden item).
C - Coordinates Event (Used to trigger cutscenes).
O - Object (either an NPC or an object of sorts, like an itemball).
W - Warp (self-explanatory).

**Comment by Rangi42** [comment]
https://github.com/pret/pokecrystal/blob/master/docs/map_event_scripts.md

**Comment by mk-pmb** [comment]
@FrenchOrange Thanks!

@Rangi42 
The document at your link doesn't (at least for me) show any of the letter overlay icons. So even if a casually interested viewer of the screenshot were able to find the document in that other, not obviously related repo, they wouldn't find a legend. Maybe you missed the "below the screenshot" part.
If we already have documentation about the UI elements, maybe you could link to that near the screenshot instead of adding a legend. That would be good enough for me.
I just checked the readme of polished-map again and could not find any link to any explanation of the UI elements shown.
