### ISSUE TITLE
[Feature Request] Guess tileset from data/maps/maps.asm

### ISSUE THREAD

**Issue by mid-kid** [Rangi42/polished-map#9]
What it says on the tin. It's annoying to have to look up the tileset name manually just as much as looking up its size.
It's not too difficult a format to parse and the file names should match the constants in lowercase sans the leading `TILESET_`.

It might be useful to tell the user if the options have been autodetected or not. Could be as simple as having "Select a tileset..." as default option.

**Comment by Rangi42** [comment]
This would be nice. Low priority though.

**Comment by Rangi42** [comment]
Implemented in 3.3.0.
